-- Catedral Experience - Recomecos
-- Estado atual: o site usa Supabase somente para Authentication do administrador.
--
-- Nao ha tabelas obrigatorias para o CMS local.
-- O conteudo editavel fica nos arquivos:
-- - src/data/musicos.json
-- - src/data/convidados.json
-- - src/data/galeria.json
-- - src/data/patrocinadores.json
--
-- No Supabase, crie apenas o usuario administrador em:
-- Authentication > Users
--
-- E-mail permitido pelo codigo:
-- desouza.webmaster@gmail.com
--
-- Para persistencia real em producao, migre os uploads para Supabase Storage
-- ou outro storage externo, pois a Vercel nao persiste arquivos gravados em runtime.
